export const POD_CONNECTION_STATUS = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  ERROR: 'ERROR',
  RECONNECTING: 'RECONNECTING',
  UNKNOWN: 'UNKNOWN',
} as const;

export type PodConnectionStatusType =
  (typeof POD_CONNECTION_STATUS)[keyof typeof POD_CONNECTION_STATUS];
